"""add created_at to booking

Revision ID: a358b8a6682c
Revises: 
Create Date: 2026-03-15 15:07:25.948980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a358b8a6682c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add created_at column to bookings table
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seat_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('seats_pkey'))
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('seat_reservations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_slot', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reservation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('seat_reservations_booking_id_fkey')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('seat_reservations_seat_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seat_reservations_pkey'))
    )
    op.create_index(op.f('ix_seat_reservations_id'), 'seat_reservations', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('booking_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('scheduled_slot', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.admission_no'], name=op.f('bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('booked_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('booked_items_booking_id_fkey')),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], name=op.f('booked_items_food_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booked_items_pkey'))
    )
    op.create_index(op.f('ix_booked_items_id'), 'booked_items', ['id'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_full', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_half', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meal_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_portions', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admin_base_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prebook_pool', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('walkin_pool', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breakfast_buffer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_walkin_only', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('food_items_pkey'))
    )
    op.create_table('users',
    sa.Column('admission_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admission_no', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_admission_no'), 'users', ['admission_no'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('holidays_pkey')),
    sa.UniqueConstraint('date', name=op.f('holidays_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('food_stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('food_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_base_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prebook_pool', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('walkin_pool', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breakfast_buffer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], name=op.f('food_stocks_food_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('food_stocks_pkey'))
    )
    # ### end Alembic commands ###
