"""Add flags and flagged_at to User model

Revision ID: a6629ca89591
Revises: 5994a82090a3
Create Date: 2026-03-31 14:26:18.568464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6629ca89591'
down_revision: Union[str, Sequence[str], None] = '5994a82090a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_seat_slot_date_uc', 'seat_reservations', ['seat_id', 'time_slot', 'reservation_date'])
    op.add_column('users', sa.Column('flags', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('flagged_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flagged_at')
    op.drop_column('users', 'flags')
    op.drop_constraint('_seat_slot_date_uc', 'seat_reservations', type_='unique')
    # ### end Alembic commands ###
