"""add_daily_expenses_and_weekly_profits

Revision ID: g001
Revises: f001
Create Date: 2026-03-31 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g001'
down_revision = 'f001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_expenses_expense_date'), 'daily_expenses', ['expense_date'], unique=True)
    
    op.create_table('weekly_profits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('total_expenses', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_profits_week_start_date'), 'weekly_profits', ['week_start_date'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_profits_week_start_date'), table_name='weekly_profits')
    op.drop_table('weekly_profits')
    op.drop_index(op.f('ix_daily_expenses_expense_date'), table_name='daily_expenses')
    op.drop_table('daily_expenses')
